url:
baseurl:

title: سارا بهروزی
title-fa: سارا بهروزی
logo: logo.png
email:
description: "سارا بهروزی"
description-fa: "سارا بهروزی"

team:
- name: سارا بهروزی
  name-fa: سارا بهروزی
  pic:
  position-fa:سارا بهروزی
  position: سارا بهروزی
  description: سارا بهروزی
  social:
  - title: githubrr
    url: https:googlehgh.com

social:
- title:
  url:
